In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib as plot

In [4]:
df=pd.read_csv("E:/DSA/task3/Combined12.csv")

In [5]:
df.head()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,971.5,0.25,9.0,7.0,10.7,0.0,0,0
1,972.3,0.97,10.5,6.7,13.5,0.0,0,0
2,972.4,0.74,6.5,3.9,9.1,0.0,0,0
3,973.2,0.15,5.1,3.7,7.7,0.0,0,0
4,975.7,0.12,5.2,2.6,8.3,0.0,0,0

In [6]:
df.tail()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
533307,1015.0,2.11,19.7,15.0,27.3,3.14,325,0
533308,1015.0,2.11,19.7,15.0,27.3,24.07,147,2
533309,1015.0,2.11,19.7,15.0,27.3,3.30,247,0
533310,1015.0,2.11,19.7,15.0,27.3,25.41,308,2
533311,1015.0,2.11,19.7,15.0,27.3,3.22,190,0

In [7]:
df.shape

(533312, 8)

In [8]:
df.columns

Index(['Pressure', 'global_radiation', 'temp_mean(c)', 'temp_min(c)',
       'temp_max(c)', 'Wind_Speed', 'Wind_Bearing', 'normalized_label'],
      dtype='str')

In [9]:
print(df.columns.tolist())

['Pressure', 'global_radiation', 'temp_mean(c)', 'temp_min(c)', 'temp_max(c)', 'Wind_Speed', 'Wind_Bearing', 'normalized_label']

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 533312 entries, 0 to 533311
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Pressure          533312 non-null  float64
 1   global_radiation  533312 non-null  float64
 2   temp_mean(c)      533312 non-null  float64
 3   temp_min(c)       533312 non-null  float64
 4   temp_max(c)       533312 non-null  float64
 5   Wind_Speed        533312 non-null  float64
 6   Wind_Bearing      533312 non-null  int64
 7   normalized_label  533312 non-null  int64
dtypes: float64(6), int64(2)
memory usage: 32.6 MB

In [11]:
df.describe()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
count,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000
mean,1011.436192,1.310346,12.646057,8.648474,16.871960,11.885974,192.501742,0.906152
std,3.241187,0.897191,6.519240,5.867740,7.692881,7.677086,101.984936,0.992549
min,971.500000,0.030000,-11.100000,-16.000000,-8.500000,0.000000,0.000000,0.000000
25%,1009.800000,0.510000,7.800000,4.500000,11.100000,6.410000,130.000000,0.000000
50%,1012.300000,1.160000,13.200000,9.400000,17.200000,11.040000,190.000000,1.000000
75%,1013.900000,2.010000,17.500000,13.300000,22.400000,15.620000,288.000000,2.000000
max,1015.000000,3.600000,28.600000,22.000000,37.000000,47.530000,359.000000,3.000000

In [12]:
df.isnull()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
533307,False,False,False,False,False,False,False,False
533308,False,False,False,False,False,False,False,False
533309,False,False,False,False,False,False,False,False
533310,False,False,False,False,False,False,False,False
533311,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Pressure            0
global_radiation    0
temp_mean(c)        0
temp_min(c)         0
temp_max(c)         0
Wind_Speed          0
Wind_Bearing        0
normalized_label    0
dtype: int64

In [16]:
da=df.dropna()

In [17]:
da.shape

(533312, 8)

In [18]:
ad.isnull().sum()

Pressure            0
global_radiation    0
temp_mean(c)        0
temp_min(c)         0
temp_max(c)         0
Wind_Speed          0
Wind_Bearing        0
normalized_label    0
dtype: int64

In [19]:
df.shape

(533312, 8)

In [23]:
nc=df.select_dtypes(include=np.number).columns
print("Numaric columns\n",nc)

Numaric columns
 Index(['Pressure', 'global_radiation', 'temp_mean(c)', 'temp_min(c)',
       'temp_max(c)', 'Wind_Speed', 'Wind_Bearing', 'normalized_label'],
      dtype='str')

In [24]:
for i in nc:
    df[i]=df[i].fillna(df[i].mean())

In [26]:
df.isnull().sum()

Pressure            0
global_radiation    0
temp_mean(c)        0
temp_min(c)         0
temp_max(c)         0
Wind_Speed          0
Wind_Bearing        0
normalized_label    0
dtype: int64

In [28]:
cate_col=df.select_dtypes(include="str").columns
print(cate_col)

Index([], dtype='str')

In [29]:
for j in cate_col:
    da[j]=da[j].fillna(da[j].mode()[0])

In [30]:
da.isnull().sum()

Pressure            0
global_radiation    0
temp_mean(c)        0
temp_min(c)         0
temp_max(c)         0
Wind_Speed          0
Wind_Bearing        0
normalized_label    0
dtype: int64

In [31]:
da.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
533307    False
533308    False
533309    False
533310    False
533311    False
Length: 533312, dtype: bool

In [32]:
da.duplicated().sum()

np.int64(16264)

In [35]:
dup=da.drop_duplicates()

In [36]:
print("Duplicate records\n",dup)

Duplicate records
         Pressure  global_radiation  temp_mean(c)  temp_min(c)  temp_max(c)  \
0          971.5              0.25           9.0          7.0         10.7
1          972.3              0.97          10.5          6.7         13.5
2          972.4              0.74           6.5          3.9          9.1
3          973.2              0.15           5.1          3.7          7.7
4          975.7              0.12           5.2          2.6          8.3
...          ...               ...           ...          ...          ...
533307    1015.0              2.11          19.7         15.0         27.3
533308    1015.0              2.11          19.7         15.0         27.3
533309    1015.0              2.11          19.7         15.0         27.3
533310    1015.0              2.11          19.7         15.0         27.3
533311    1015.0              2.11          19.7         15.0         27.3

        Wind_Speed  Wind_Bearing  normalized_label
0             0.00             0                 0
1             0.00             0                 0
2             0.00             0                 0
3             0.00             0                 0
4             0.00             0                 0
...            ...           ...               ...
533307        3.14           325                 0
533308       24.07           147                 2
533309        3.30           247                 0
533310       25.41           308                 2
533311        3.22           190                 0

[517048 rows x 8 columns]

In [38]:
da["global_radiation"].dtypes

dtype('float64')

In [39]:
da['MinTemp']=da['global_radiation'].astype(float)

KeyError: 'MinTemp'